server:
  port: 8183
  tomcat:
    max-threads: 1000
    accept-count: 1000
    max-connections: 2000
    uri-encoding: UTF-8
  servlet:
    context-path: /mask-auth
spring:
  profiles:
    active: ${cn.pro.active:dev}