spring:
  datasource:
    url: jdbc:mysql://119.3.30.5:3307/spring?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: root
    initialization-mode: always
server:
  port: 2233

mybatis:
  mapper-locations: classpath*:mapping/**/*.xml
  config-location: classpath:SqlMapConfig.xml