dfs:
  url: 119.3.30.5:8181
fdfs:
  connectTimeout: 600
  soTimeout: 1500
  thumbImage:
    height: 150
    width: 150
  trackerList:
    - 119.3.30.5:12050


spring:
  sleuth:
    sampler:
      percentage: 1.0
    web:
      client:
        enabled: true
  zipkin:
    base-url: http://119.3.30.5:9411/
    sender:
      type: kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: 119.3.30.5:9092
  kafka:
    bootstrap-servers: 119.3.30.5:9092
  redis:
    host: 42.192.182.126
    port: 6379
    password: 1659868245
  #  data:
  #    mongodb:
  #      uri: mongodb://94.191.83.120:27017/mall   #114.115.171.119
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: mask-account
shiro:
  maxAge:
    day: 10
company:
  images:
    login-logo:
    logo:
    login-bg:
wx:
  app-id: wxd2bf68f18c88352a
  app-secret: 6121b5aeca6adb9df720f8618bfd0d5b
  redirect-uri: https://mask.cn
  mchId: xxxxxxxx
  key: xxxxxxxx
  certPath:
  notify_url: http://thesunbig.imwork.net/wx/notify
  wap_url: https://pay.qq.com
  spbill_create_ip: 127.0.0.1

goods:
  pic:
    domain: http://demo5.tp-shop.cn


eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@42.192.182.126:8763/eureka/
    register-with-eureka: true
    fetch-registry: true
    #instance:
    #hostname: account.h
    #ip-address: 94.191.83.120
    #prefer-ip-address: true
    #instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 5000
  OkToRetryOnAllOperations: false
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 0

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: debug