server:
  port: 2237
spring:
  datasource:
    url: jdbc:mysql://119.3.30.5/spring
    username: admin
    password: 1659868245
    initialization-mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/certs
claim:
  aud: fitnessapp

